import './css/style.css'
import { Inter } from 'next/font/google'
import localFont from 'next/font/local'
import Theme from './theme-provider'

const inter = Inter({
	subsets: ['latin'],
	variable: '--font-inter',
	display: 'swap'
})

const aspekta = localFont({
	src: [
		{
			path: '../../public/fonts/Aspekta-500.woff2',
			weight: '500',
		},
		{
			path: '../../public/fonts/Aspekta-650.woff2',
			weight: '650',
		},
	],
	variable: '--font-aspekta',
	display: 'swap',
})

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={`${inter.variable} ${aspekta.variable} font-inter antialiased bg-white text-slate-800 dark:bg-slate-900 dark:text-slate-200 tracking-tight`}>
				<Theme>
					<div className="max-w-7xl mx-auto">
						<div className="min-h-screen flex">
							{ /* Main content */}
							<main className="grow overflow-hidden px-6">
								<div className="w-full h-full max-w-[1072px] mx-auto flex flex-col">
									{children}
								</div>
							</main>
						</div>
					</div>
				</Theme>
			</body>
		</html>
	)
}
